### ISSUE TITLE
Is it still alive?

### ISSUE THREAD

**Issue by TheBricktop** [ConstellationLanguage/Constellation#71]
Hello really liking this project, anybody still working on it?

**Comment by AntoineCharton** [comment]
Hello TheBricktop

Tthere is a couple of reason why I took a break from this project. 

The first reason and main one is because currently I am working on a personal project and it's taking me a lot of time. 

The second reason is that unity released it's stock visual scripting tool. It doesn't mean Constellation is uselless but I'm gonna have to redefine what is the project purpose. My goal is not to compete with unity features but to add something that they don't offer. I have a couple of ideas but no time right now to make them a reallity.

So right now I'm not actively working on it. However if you need a non core related feature I can spend some time helping you. So for example if you need a node or a bug fix no problem submit an issue here and I will check it. I also check pull requests. If you submit one I will review it and merge it to the core. 

So if you want a date I would say I will have more time after September. 

Let me know if you have any other questions :)

**Comment by AntoineCharton** [comment]
See discord to check what I am working on :)
